services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/tmp:/prometheus
      - ./prometheus/config:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml --log.level=debug
    # THIS LINE IS KEY:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest-ubuntu
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/tmp:/var/lib/grafana